project_id = "wassazjsbznidfaesbbu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.process-card-payment]
verify_jwt = true

[functions.process-order-refund]
verify_jwt = true

[functions.point-pos-manager]
verify_jwt = false

[functions.point-terminal-manager]
verify_jwt = false

[functions.process-sale-inventory]
verify_jwt = true

[functions.mercadopago-store-manager]
verify_jwt = false

[functions.mercadopago-order-manager]
verify_jwt = false