// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wassazjsbznidfaesbbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhc3NhempzYnpuaWRmYWVzYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTY1NzAsImV4cCI6MjA3MzU3MjU3MH0.5T3KDzk4zkVxTGTuq8iqmtx3GnebaGHgZe_c944g3c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});